services:
  coffee-board-db:
    container_name: coffee-board-db
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  coffee-board-cache:
    container_name: coffee-board-cache
    image: redis:7.4.2-alpine
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis-data:/data
  coffe-board-mailpit:
    container_name: coffee-board-mailpit
    image: axllent/mailpit:v1.25
    volumes:
      - ./mailpit:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
