import {
	LuAlignLeft,
	LuArrowLeft,
	LuBell,
	LuBox,
	LuBoxes,
	LuChevronDown,
	LuChevronUp,
	LuCirclePlus,
	LuCircleX,
	LuComponent,
	LuEllipsis,
	LuEye,
	LuFile,
	LuFileImage,
	LuGithub,
	LuLayoutDashboard,
	LuLoaderCircle,
	LuMoon,
	LuPaperclip,
	LuPencil,
	LuSearch,
	LuSun,
	LuTrash2,
	LuTruck,
	LuUsersRound,
	LuWrench,
} from "react-icons/lu"

const Icons = {
	Misc: {
		Error: LuCircleX,
		Box: LuBox,
		Boxes: LuBoxes,
		Component: LuComponent,
		Sun: LuSun,
		Moon: LuMoon,
		Menu: LuEllipsis,
		Clip: LuPaperclip,
		Image: LuFileImage,
		AlignLeft: LuAlignLeft,
	},
	Navbar: {
		Home: LuLayoutDashboard,
		Load: LuTruck,
		Users: LuUsersRound,
	},
	Actions: {
		Add: LuCirclePlus,
		Edit: LuPencil,
		Loading: LuLoaderCircle,
		Delete: LuTrash2,
		Search: LuSearch,
		File: LuFile,
		DropdownOpen: LuChevronDown,
		DropdownClosed: LuChevronUp,
		Show: LuEye,
		Back: LuArrowLeft,
		Settings: LuWrench,
		Notification: LuBell,
	},
	Social: {
		Github: LuGithub,
	},
}

export default Icons
