import {
	LuAlignLeft,
	LuArchive,
	LuArrowDownUp,
	LuArrowLeft,
	LuBell,
	LuBookText,
	LuBox,
	LuBoxes,
	LuCalendarDays,
	LuCheck,
	LuChevronDown,
	LuChevronLeft,
	LuChevronRight,
	LuChevronsLeft,
	LuChevronsRight,
	LuChevronUp,
	LuCirclePlus,
	LuCircleX,
	LuComponent,
	LuDatabaseZap,
	LuEllipsis,
	LuEllipsisVertical,
	LuEye,
	LuFile,
	LuFileImage,
	LuFolder,
	LuFolderOpen,
	LuGithub,
	LuGlobeLock,
	LuLayoutDashboard,
	LuLoaderCircle,
	LuLogOut,
	LuMoon,
	LuPaperclip,
	LuPencil,
	LuRefreshCcw,
	LuSearch,
	LuSun,
	LuTags,
	LuTrash2,
	LuTruck,
	LuUsersRound,
	LuWrench,
	LuX,
} from "react-icons/lu"

const Icons = {
	Misc: {
		Private: LuGlobeLock,
		Archive: LuArchive,
		Books: LuBookText,
		Error: LuCircleX,
		Box: LuBox,
		Boxes: LuBoxes,
		Refresh: LuRefreshCcw,
		Component: LuComponent,
		Sun: LuSun,
		Moon: LuMoon,
		Menu: LuEllipsis,
		MenuVertical: LuEllipsisVertical,
		Clip: LuPaperclip,
		Image: LuFileImage,
		AlignLeft: LuAlignLeft,
		Calendar: LuCalendarDays,
		Dashboard: LuLayoutDashboard,
		Users: LuUsersRound,
		Tags: LuTags,
		UpDown: LuArrowDownUp,
		NoData: LuDatabaseZap,
		Folder: LuFolder,
		FolderOpen: LuFolderOpen,
		File: LuFile,
		Logout: LuLogOut,
	},
	Navbar: {
		Home: LuLayoutDashboard,
		Load: LuTruck,
		Users: LuUsersRound,
	},
	Actions: {
		Add: LuCirclePlus,
		Edit: LuPencil,
		Loading: LuLoaderCircle,
		Delete: LuTrash2,
		Search: LuSearch,
		File: LuFile,
		Accept: LuCheck,
		FirstPage: LuChevronsLeft,
		LastPage: LuChevronsRight,
		DropdownOpen: LuChevronDown,
		DropdownClosed: LuChevronUp,
		PaginationLeft: LuChevronLeft,
		PaginationRight: LuChevronRight,
		Show: LuEye,
		Back: LuArrowLeft,
		Settings: LuWrench,
		Notification: LuBell,
		Close: LuX,
	},
	Social: {
		Github: LuGithub,
	},
}

export default Icons
