export const PERMISSIONS = Object.freeze({
	ReadTags: { id: 1, name: "Read Tags", action: "GET" },
	CreateTag: { id: 2, name: "Create Tag", action: "POST" },
	UpdateTag: { id: 3, name: "Update Tag", action: "PUT" },
	DeleteTag: { id: 4, name: "Delete Tag", action: "DELETE" },
	ReadPriority: { id: 5, name: "Read Priority", action: "GET" },
	CreatePriority: { id: 6, name: "Create Priority", action: "POST" },
	UpdatePriority: { id: 7, name: "Update Priority", action: "PUT" },
	DeletePriority: { id: 8, name: "Delete Priority", action: "DELETE" },
	ReadProjects: { id: 9, name: "Read Projects", action: "GET" },
	CreateProject: { id: 10, name: "Create Project", action: "POST" },
	UpdateProject: { id: 11, name: "Update Project", action: "PUT" },
	DeleteProject: { id: 12, name: "Delete Project", action: "DELETE" },
	ReadBoards: { id: 13, name: "Read Boards", action: "GET" },
	CreateBoards: { id: 14, name: "Create Boards", action: "POST" },
	UpdateBoards: { id: 15, name: "Update Boards", action: "PUT" },
	DeleteBoards: { id: 16, name: "Delete Boards", action: "DELETE" },
	ReadBoardDets: { id: 17, name: "Read Board Dets", action: "GET" },
	CreateBoardDets: { id: 18, name: "Create Board Dets", action: "POST" },
	UpdateBoardDets: { id: 19, name: "Update Board Dets", action: "PUT" },
	DeleteBoardDets: { id: 20, name: "Delete Board Dets", action: "DELETE" },
	ReadCalendar: { id: 21, name: "Read Calendar", action: "GET" },
	CreateCalendar: { id: 22, name: "Create Calendar", action: "POST" },
	UpdateCalendar: { id: 23, name: "Update Calendar", action: "PUT" },
	DeleteCalendar: { id: 24, name: "Delete Calendar", action: "DELETE" },
	ReadSettings: { id: 25, name: "Read Settings", action: "GET" },
	UpdateSettings: { id: 26, name: "Update Settings", action: "POST" },
	ReadTasks: { id: 27, name: "Read Tasks", action: "GET" },
	CreateTasks: { id: 28, name: "Create Tasks", action: "POST" },
	UpdateTasks: { id: 29, name: "Update Tasks", action: "PUT" },
	DeleteTasks: { id: 30, name: "Delete Tasks", action: "DELETE" },
})
